version: "3.3"
services:
  scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  frontend:
    restart: on-failure
    environment:
      - BACKEND_URL=https://greenheart.apisc.host
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"

