services:
  scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  frontend:
    restart: on-failure
    environment:
      - BACKEND_URL=http://scheduler:5000
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  demo_worker:
    replicas: 0
    restart: on-failure
    environment:
      - SCHEDULER_URL=http://scheduler:5001
      - OPENAI_API_KEY
    build:
      context: workers
      dockerfile: demo_worker/Dockerfile

  ai_worker:
    restart: on-failure
    environment:
      - SCHEDULER_URL=http://scheduler:5001
      - OPENAI_API_KEY
    build:
      context: workers
      dockerfile: ai_worker/Dockerfile
