services:
  scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  demo_worker:
    restart: on-failure
    environment:
      - SCHEDULER_URL=http://scheduler:5001
    build:
      context: workers
      dockerfile: demo_worker/Dockerfile
